---
version: '3.7'

services:
  devenv:
    image: idelchi/devenv:local
    container_name: devenv
    hostname: devenv
    ports:
      # <host:container>
      - '9090:6419' # grip
    network_mode: bridge
    user: user
    volumes:
      - .:/home/user/ws
    extra_hosts:
      - host:host-gateway
    working_dir: /home/user/ws
