version: '3'

vars:
  SETTINGS_DIR: .devenv

includes:
  common:
    taskfile: '{{.SETTINGS_DIR}}/Taskfile.yml'
    vars:
      CONFIG_DIR: '{{.SETTINGS_DIR}}/config'
      SCRIPTS_DIR: '{{.SETTINGS_DIR}}/scripts'
    aliases:
      - ci

silent: true

output: prefixed

tasks:
  clean:
    - task: common:aux:clean

  info:
    - task: common:git

  format:
    - task: common:format

  lint:
    deps:
      - common:lint

  docker:
    - task: common:docker

  all:
    desc: run all available tasks
    cmds:
      - task: clean
      - task: info
      - task: format
      - task: lint

  default:
    desc: clean, format & lint
    cmds:
      - task: info
      - task: format
      - task: lint

  push:
    - task: common:push

  update:
    - task: common:git:update
